name: Build and Deploy GH Pages
on: [push, workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          submodules: true

      - name: Install and Build engine
        working-directory: ./engine
        run: |
          npm install
          npm run build

      - name: Install and Build app
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: dist
